name: Build Anomaly Training Image
on:
  workflow_dispatch:
  push:
    branches: [main, develop]
    paths:
      - 'models/anomaly/**'

jobs:
  build-anomaly-training-image:
    uses: ./.github/workflows/build-docker-image.yaml
    with:
      image_name: "anomaly-train"
      dockerfile_path: "./models/anomaly/Dockerfile.train"
      context_path: "./models/anomaly"
      image_tag_suffix: "anomaly-train"
      